idf_component_register(SRCS "ui_http_server.c"
                       INCLUDE_DIRS "include"
                       REQUIRES esp_http_server settings_manager dsp_processor_settings tas5805m_settings network_interface
                       PRIV_REQUIRES custom_board
                       EMBED_TXTFILES html/index.html
                                      html/index.js
                                      html/settings-ui.js
                                      html/styles.css
                                      html/general-settings.html
                                      html/dsp-settings.html
                                      html/dac-settings.html
                                      html/eq-settings.html
                                      html/wifi-settings.html
                       EMBED_FILES html/favicon.ico)
